project:
  type: website
  output-dir: docs

website:
  title: "testwebsite1"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - hww.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



