project:
  type: website

website:
  title: "testwebsite1"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - hw1.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



