project:
  type: website
  output-dir: docs

website:
  page-navigation: true
  title: "woong.2"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: posts/index.qmd
        text: Blog
        
format:
  html:
    theme: cosmo
    toc: true


